const Packs = [
    {
        nome: '5 Card Pack Rare',
        caminho: 'bepro-pack',
        preco: 200,
        vizualizacoes: '10k',
        emEstoque: 30,
        imagem: '/card-pack-bepro.png',
        descricao: 'Pack composed of 100% rare cards',
        featured: true,
        rare: true,
        saleSoon: false,
    },
    {
        nome: '5 Card Pack Rare',
        caminho: 'moonriver-pack',
        preco: 200,
        vizualizacoes: '10k',
        emEstoque: 30,
        imagem: '/card-pack-moonriver.png',
        descricao: 'Pack composed of 100% rare cards',
        featured: true,
        rare: true,
        saleSoon: true,
    },
    {
        nome: '5 Card Pack Common',
        caminho: '5-card-pack-common',
        preco: 50,
        vizualizacoes: '10k',
        emEstoque: 5,
        imagem: '/card-pack-common-5.png',
        descricao: 'Pack composed of 80% common cards and 20% rare cards',
        featured: false,
        rare: false,
        saleSoon: true,
    },
    {
        nome: '5 Card Pack Uncommon',
        caminho: '5-card-pack-uncommon',
        preco: 70,
        vizualizacoes: '10k',
        emEstoque: 0,
        imagem: '/card-pack-uncommon-5.png',
        descricao: 'Pack composed of 60% common cards and 40% rare cards',
        featured: false,
        rare: false,
        saleSoon: true,
    },
    {
        nome: '5 Card Pack Rare',
        caminho: '5-card-pack-rare',
        preco: 100,
        vizualizacoes: '10k',
        emEstoque: 5,
        imagem: '/card-pack-rare-5.png',
        descricao: 'Pack composed of 40% common cards and 60% rare cards',
        featured: true,
        rare: true,
        saleSoon: true,
    },
    {
        nome: '20 Card Pack Common',
        caminho: '20-card-pack-common',
        preco: 180,
        vizualizacoes: '10k',
        emEstoque: 20,
        imagem: '/card-pack-common-20.png',
        descricao: 'Pack composed of 80% common cards and 20% rare cards',
        featured: false,
        rare: false,
        saleSoon: true,
    },
    {
        nome: '20 Card Pack Uncommon',
        caminho: '20-card-pack-uncommon',
        preco: 255,
        vizualizacoes: '10k',
        emEstoque: 20,
        imagem: '/card-pack-uncommon-20.png',
        descricao: 'Pack composed of 60% common cards and 40% rare cards',
        featured: false,
        rare: false,
        saleSoon: true,
    },
    {
        nome: '20 Card Pack Rare',
        caminho: '20-card-pack-rare',
        preco: 370,
        vizualizacoes: '10k',
        emEstoque: 20,
        imagem: '/card-pack-rare-20.png',
        descricao: 'Pack composed of 40% common cards and 60% rare cards',
        featured: true,
        rare: true,
        saleSoon: true,
    }
]

export default Packs
