// "http://localhost:5000"
// "https://jmibook.onrender.com"
export const proxy = "https://jmibook.onrender.com"
export const socketProxy = "https://jmibook.onrender.com"
export const ipfsGateway = "https://cloudflare-ipfs.com/ipfs/"
